ArtGallery/ArtGallery/Areas/Administration/Controllers/DashboardController.cs
namespace ArtGallery.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class DashboardController : AdministrationController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ArtGallery/ArtGallery/Controllers/AboutController.cs
using ArtGallery.Core.Models.FaqEntity;
using Microsoft.AspNetCore.Mvc;

namespace ArtGallery.Controllers
{
    public class AboutController : BaseController
    {
        private readonly IAboutService aboutService;

        public AboutController(IAboutService aboutService)
        {
            this.aboutService = aboutService;
        }

        public async Task<IActionResult> Index()
        {
            var faq = await aboutService.GetAllFaqsAsync<FaqViewModel>();

            return View(faq);
        }
    }
}

ArtGallery/ArtGallery/Controllers/EventController.cs
namespace ArtGallery.Controllers
{
    using ArtGallery.Core.Contracts;
    using ArtGallery.Core.Models.Events;
    using ArtGallery.ModelBinders;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class EventController : BaseController
    {
        private readonly IEventService events;

        public EventController(IEventService eventservice)
        {
            this.events = eventservice;
        }

        [Route("/Event/AllEvents")]
        [AllowAnonymous]
        public IActionResult AllEvents(AllEventListViewModel model)
        {
            var modelView = this.events.GetAllEvents(model.EventId);
            // changes done by bhavin.
            var allEvents = modelView.Select(e => new AllEventListViewModel
            {
                Name = e.Name,
                Date = e.Date.ToString(),
                Type = e.Type,
                Description = e.Description,
            }).ToList();

            return View(allEvents);
        }

        [Route("/Event/EventDetails/{eventId}")]
        public IActionResult EventDetails(int eventId)
        {
            if (eventId == null)
            {
                return new StatusCodeResult(404);
            }

            var eventDetails = this.events.GetEventDetailsByIdAsync<EventViewModel>(eventId);

            return this.View(eventDetails);
        }

        public IActionResult SetCultureCookie(string cltr, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cltr)),
                new CookieOptions
                {
                    Expires = DateTime.UtcNow.AddYears(1),
                    SameSite = SameSiteMode.Strict
                });

            return LocalRedirect(returnUrl);
        }
    }
}

ArtGallery/ArtGallery/Controllers/UserController.cs
namespace ArtGallery.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using ArtGallery.Common;
    using System.Security.Claims;
    using ArtGallery.Core.Contracts;
    using ArtGallery.Core.Models.Users;
    using static ArtGallery.Common.GlobalConstants;
    using ArtGallery.Core.Mapping;

    [Authorize(Roles = GlobalConstants.UserRoleName)]
    public class UserController : BaseController
    {
        private readonly IUserService userService;
        private readonly ICloudinaryService cloudinary;

        public UserController(IUserService userService, ICloudinaryService cloudinary)
        {
            this.userService = userService;
            this.cloudinary = cloudinary;
        }
        
        public IActionResult SetCultureCookie(string cltr, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cltr)),
                new CookieOptions
                {
                    Expires = DateTime.UtcNow.AddYears(1),
                    SameSite = SameSiteMode.Strict
                });

            return LocalRedirect(returnUrl);
        }
    }
}

ArtGallery/ArtGallery/Areas/Administration/Views/Dashboard/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Dashboard";
    Layout = "/Areas/Administration/Views/Shared/_AdminLayout.cshtml";
}

<div class="mt-2">
    <div class="nav-header">Admin Access</div>
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
            <a href="/" class="nav-link btn-outline-info"> <i class="fas fa-house-user"></i> Home </a>
        </li>
        <li class="nav-item menu-is-opening menu-open">
            <a href="#" class="nav-link active">
                <i class="nav-icon fas fa-book"></i>
                <p>
                    Users
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview" style="display: block;">
                <li class="nav-item">
                    <a asp-area="Administration" asp-controller="User" asp-action="CreateRole" class="nav-link btn-outline-info">
                        <i class="far fa-circle nav-icon"></i> Create Role
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Administration" asp-controller="User" asp-action="ManageRoles" class="nav-link btn-outline-info">
                        <i class="far fa-circle nav-icon"></i> Manage Roles
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Administration" asp-controller="User" asp-action="ManageUsers" class="nav-link btn-outline-info">
                        <i class="far fa-circle nav-icon"></i> Manage Users
                    </a>
                </li>
            </ul>
        </li>

        <li class="nav-item menu-is-opening menu-open">
            <a href="#" class="nav-link active">
                <i class="nav-icon fas fa-book"></i>
                <p>
                    About
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview" style="display: block;">
                <li class="nav-item">
                    <a asp-area="Administration" asp-controller="About" asp-action="Create" class="nav-link btn-outline-info">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Create FAQ</p>
                    </a>
                </li>
            <!--   <li class="nav-item">
                    <a asp-area="Administration" asp-controller="About" asp-action="Edit" class="nav-link btn-outline-info">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Edit FAQ</p>
                    </a>
                </li>  -->
            </ul>
        </li>

    <!-- <li class="nav-item menu-is-opening menu-open">
            <a href="#" class="nav-link active">
                <i class="nav-icon fas fa-book"></i>
                <p>
                    Events
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview" style="display: block;">
               <li class="nav-item">
                    <a asp-area="Administration" asp-controller="Event" asp-action="Create" class="nav-link btn-outline-info">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Create Event</p>
                    </a>
                </li>  
                <li class="nav-item">
                    <a asp-area="Administration" asp-controller="Event" asp-action="Edit" class="nav-link btn-outline-info">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Edit Event</p>
                    </a>
                </li> 
            </ul> 
        </li>  -->
    </ul>
</div>